#!/bin/bash

# Export the ANSI colour codes so we can highlight text in the terminal

colour_black="\033[0;30m"
colour_darkgray="\033[1;30m"
colour_red="\033[0;31m"
colour_lightred="\033[1;31m"
colour_green="\033[0;32m"
colour_lightgreen="\033[1;32m"
colour_orange="\033[0;33m"
colour_yellow="\033[1;33m"
colour_blue="\033[0;34m"
colour_lightblue="\033[1;34m"
colour_purple="\033[0;35m"
colour_lightpurple="\033[1;35m"
colour_cyan="\033[0;36m"
colour_lightcyan="\033[1;36m"
colour_lightgray="0;\033[37 m"
colour_white="\033[1;37m"

# Export codes for making text bold, italic, etc.

bold="\e[1m"
italic="\e[3m"
underline="\e[4"
strikethrough="\e[9"
normal="\e[0m"
