#!/bin/bash

# Export the ANSI color codes so we can highlight text in the terminal

color_black="\033[0;30m"
color_darkgray="\033[1;30m"
color_red="\033[0;31m"
color_lightred="\033[1;31m"
color_green="\033[0;32m"
color_lightgreen="\033[1;32m"
color_orange="\033[0;33m"
color_yellow="\033[1;33m"
color_blue="\033[0;34m"
color_lightblue="\033[1;34m"
color_purple="\033[0;35m"
color_lightpurple="\033[1;35m"
color_cyan="\033[0;36m"
color_lightcyan="\033[1;36m"
color_lightgray="0;\033[37 m"
color_white="\033[1;37m"

# Export codes for making text bold, italic, etc.

bold="\e[1m"
italic="\e[3m"
underline="\e[4"
strikethrough="\e[9"
normal="\e[0m"
