#!/bin/bash

# package
# Builds binaries for alpine, linux, macos and win
# 
# Usage: scripts/package
# 
# Remember to run this script from the root of the project!

# Fail fast
set -e

# ANSI colour codes so we can highlight text in the terminal
colour_red="\033[0;31m"
colour_green="\033[0;32m"
colour_blue="\033[0;34m"
colour_cyan="\033[0;36m"

# Escape codes for making text bold and returning it back to normal
bold="\e[1m"
normal="\e[0m"

# Display a help message
function help {
	echo -e "${colour_cyan}${bold}package${normal}"
	echo -e "${colour_blue}Builds binaries for alpine, linux, macos and win${normal}"
	echo -e ""
	echo -e "Usage: ${colour_cyan}scripts/package${normal}"
	echo -e ""
	echo -e "${colour_cyan}Remember to run this script from the root of the project!${normal}"
}

# Main function
function main {
	# If the first argument is help, show help and exit
	if [ "$1" = "help" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
		help
		exit
	fi

	# Else run the script
	# First build
	yarn build
	cp ./package.json ./dist/package.json
	# Then run pkg to generate binaries
	yarn pkg .
}

# Run the script, accepting only one argument
main "$1"
